apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: helm
    repoURL: https://github.com/gonzaloacosta/voting-app.git
    targetRevision: HEAD
    helm:
      values: |
        result:
          image:
            tag: latest
          ingressHost: result.192.168.64.6.nip.io
        vote:
          image:
            tag: latest 
          ingressHost: vote.192.168.64.6.nip.io
        worker:
          image:
            tag: latest
      version: v3
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
